DjangoHUD/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('DjangoHUDApp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'DjangoHUDApp.views.handler404'

DjangoHUDApp/urls.py
from django.urls import path

from . import views

app_name = 'DjangoHUDApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('404/', views.error404, name='error404'),
    path('analytics/', views.analytics, name='analytics'),
    path('email/inbox/', views.emailInbox, name='emailInbox'),
    path('email/detail/', views.emailDetail, name='emailDetail'),
    path('email/compose/', views.emailCompose, name='emailCompose'),
    path('widgets/', views.widgets, name='widgets'),
    path('pos/customer-order/', views.posCustomerOrder, name='posCustomerOrder'),
    path('pos/kitchen-order/', views.posKitchenOrder, name='posKitchenOrder'),
    path('pos/counter-checkout/', views.posCounterCheckout, name='posCounterCheckout'),
    path('pos/table-booking/', views.posTableBooking, name='posTableBooking'),
    path('pos/menu-stock/', views.posMenuStock, name='posMenuStock'),
    path('ui/bootstrap/', views.uiBootstrap, name='uiBootstrap'),
    path('ui/buttons/', views.uiButtons, name='uiButtons'),
    path('ui/card/', views.uiCard, name='uiCard'),
    path('ui/icons/', views.uiIcons, name='uiIcons'),
    path('ui/modal-notifications/', views.uiModalNotifications, name='uiModalNotifications'),
    path('ui/typography/', views.uiTypography, name='uiTypography'),
    path('ui/tabs-accordions/', views.uiTabsAccordions, name='uiTabsAccordions'),
    path('form/elements/', views.formElements, name='formElements'),
    path('form/plugins/', views.formPlugins, name='formPlugins'),
    path('form/wizards/', views.formWizards, name='formWizards'),
    path('table/elements/', views.tableElements, name='tableElements'),
    path('table/plugins/', views.tablePlugins, name='tablePlugins'),
    path('chart/js/', views.chartJs, name='chartJs'),
    path('chart/apex/', views.chartApex, name='chartApex'),
    path('map/', views.map, name='map'),
    path('layout/starter', views.layoutStarter, name='layoutStarter'),
    path('layout/fixed-footer', views.layoutFixedFooter, name='layoutFixedFooter'),
    path('layout/full-height', views.layoutFullHeight, name='layoutFullHeight'),
    path('layout/full-width', views.layoutFullWidth, name='layoutFullWidth'),
    path('layout/boxed-layout', views.layoutBoxedLayout, name='layoutBoxedLayout'),
    path('layout/collapsed-sidebar', views.layoutCollapsedSidebar, name='layoutCollapsedSidebar'),
    path('layout/top-nav', views.layoutTopNav, name='layoutTopNav'),
    path('layout/mixed-nav', views.layoutMixedNav, name='layoutMixedNav'),
    path('layout/mixed-nav-boxed-layout', views.layoutMixedNavBoxedLayout, name='layoutMixedNavBoxedLayout'),
    path('page/scrum-board', views.pageScrumBoard, name='pageScrumBoard'),
    path('page/product', views.pageProduct, name='pageProduct'),
    path('page/product-details', views.pageProductDetails, name='pageProductDetails'),
    path('page/order', views.pageOrder, name='pageOrder'),
    path('page/order-details', views.pageOrderDetails, name='pageOrderDetails'),
    path('page/gallery', views.pageGallery, name='pageGallery'),
    path('page/search-results', views.pageSearchResults, name='pageSearchResults'),
    path('page/coming-soon', views.pageComingSoon, name='pageComingSoon'),
    path('page/error', views.pageError, name='pageError'),
    path('page/login', views.pageLogin, name='pageLogin'),
    path('page/register', views.pageRegister, name='pageRegister'),
    path('page/messenger', views.pageMessenger, name='pageMessenger'),
    path('page/data-management', views.pageDataManagement, name='pageDataManagement'),
    path('page/file-manager', views.pageFileManager, name='pageFileManager'),
    path('page/pricing', views.pagePricing, name='pagePricing'),
    path('profile/', views.profile, name='profile'),
    path('calendar/', views.calendar, name='calendar'),
    path('settings/', views.settings, name='settings'),
    path('helper/', views.helper, name='helper'),
    path('logout/', views.logout_view, name='logout'),
    path('create-sale/', views.create_sale, name='create_sale'),
    
    
    #products management
    path('test-static/', views.test_static, name='test_static'),
    path('products/', views.product_management, name='product_management'),
    path('products/template/', views.download_template, name='download_template'),
    path('products/list/', views.product_list, name='product_list'),
    path('products/add/', views.product_management, name='product_management'),
    path('products/edit/<int:product_id>/', views.product_edit, name='product_edit'),
    path('products/delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('products/<int:product_id>/', views.product_details, name='product_details'),
    path('products/<int:product_id>/stock/', views.update_stock, name='update_stock'),
    path('store/', views.store_view, name='store_view'),
]

DjangoHUDApp/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.db.models import Sum, F, Q
from django.views.decorators.http import require_POST
import json
from django.db import connection
from django.contrib.auth.decorators import login_required
import csv
from django.core.files.storage import default_storage
from .forms import ProductForm, BulkProductUploadForm, StockUpdateForm

from DjangoHUDApp.models import Customer, Product, Sale, SaleItem, Store, Category, ProductVariant

def index(request):
    context = {
    "appContentFullWidth": 1,
    
	}
    return render(request, "pages/index.html", context)

def analytics(request):
	return render(request, "pages/analytics.html")

def emailInbox(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": "p-3"
	}
	return render(request, "pages/email-inbox.html", context)

def emailDetail(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": "p-3"
	}
	return render(request, "pages/email-detail.html", context)

def emailCompose(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": "p-3"
	}
	return render(request, "pages/email-compose.html", context)

def widgets(request):
	return render(request, "pages/widgets.html")

# create sale
def posCustomerOrder(request):
    search_query = request.GET.get('search', '')
    store_products = Product.objects.all()
    customers = Customer.objects.all()
    
    # search query
    if search_query:
        store_products = store_products.filter(
            Q(name__icontains=search_query) |
            Q(description__icontains=search_query)
        )
    
    context = {
        "store_products": store_products,
        "customers": customers,
        "search_query": search_query,
        'appSidebarHide': 1,
        'appHeaderHide': 1,
        'appContentFullHeight': 1,
        'appContentClass': "p-1 ps-xl-4 pe-xl-4 pt-xl-3 pb-xl-3",
    }
    return render(request, "pages/pos-customer-order.html", context)

@require_POST
def create_sale(request):
    try:
        data = json.loads(request.body)
        customer_id = data.get('customer_id')
        location = data.get('location')
        items = data.get('items', [])
        payment_status = data.get('payment_status', 'pending')
        notes = data.get('notes', '')

        # Create sale
        sale = Sale.objects.create(
            customer_id=customer_id,
            location=location,
            payment_status=payment_status,
            notes=notes
        )

        # Create sale items
        for item in items:
            product = Product.objects.get(id=item['product_id'])
            SaleItem.objects.create(
                sale=sale,
                product=product,
                quantity=item['quantity'],
                unit_price=product.price,
                discount=item.get('discount', 0)
            )

            # Update store quantity
            store, created = Store.objects.get_or_create(product=product)
            store.quantity -= item['quantity']
            store.save()

        return JsonResponse({
            'status': 'success',
            'sale_id': sale.id,
            'message': 'Sale created successfully'
        })
    except Exception as e:
        return JsonResponse({
            'status': 'error',
            'message': str(e)
        }, status=400)

def posKitchenOrder(request):
	context = {
		"appSidebarHide": 1, 
		"appHeaderHide": 1,  
		"appContentFullHeight": 1,
		"appContentClass": "p-1 ps-xl-4 pe-xl-4 pt-xl-3 pb-xl-3"
	}
	return render(request, "pages/pos-kitchen-order.html", context)

def posCounterCheckout(request):
	context = {
		"appSidebarHide": 1, 
		"appHeaderHide": 1,  
		"appContentFullHeight": 1,
		"appContentClass": "p-1 ps-xl-4 pe-xl-4 pt-xl-3 pb-xl-3"
	}
	return render(request, "pages/pos-counter-checkout.html", context)

def posTableBooking(request):
	context = {
		"appSidebarHide": 1, 
		"appHeaderHide": 1,  
		"appContentFullHeight": 1,
		"appContentClass": "p-1 ps-xl-4 pe-xl-4 pt-xl-3 pb-xl-3"
	}
	return render(request, "pages/pos-table-booking.html", context)

def posMenuStock(request):
	context = {
		"appSidebarHide": 1, 
		"appHeaderHide": 1,  
		"appContentFullHeight": 1,
		"appContentClass": "p-1 ps-xl-4 pe-xl-4 pt-xl-3 pb-xl-3"
	}
	return render(request, "pages/pos-menu-stock.html", context)

def uiBootstrap(request):
	return render(request, "pages/ui-bootstrap.html")

def uiButtons(request):
	return render(request, "pages/ui-buttons.html")

def uiCard(request):
	return render(request, "pages/ui-card.html")

def uiIcons(request):
	return render(request, "pages/ui-icons.html")

def uiModalNotifications(request):
	return render(request, "pages/ui-modal-notifications.html")

def uiTypography(request):
	return render(request, "pages/ui-typography.html")

def uiTabsAccordions(request):
	return render(request, "pages/ui-tabs-accordions.html")

def formElements(request):
	return render(request, "pages/form-elements.html")

def formPlugins(request):
	return render(request, "pages/form-plugins.html")

def formWizards(request):
	return render(request, "pages/form-wizards.html")

def tableElements(request):
	return render(request, "pages/table-elements.html")

def tablePlugins(request):
	return render(request, "pages/table-plugins.html")

def chartJs(request):
	return render(request, "pages/chart-js.html")

def chartApex(request):
	return render(request, "pages/chart-apex.html")

def map(request):
	return render(request, "pages/map.html")

def layoutStarter(request):
	return render(request, "pages/layout-starter.html")

def layoutFixedFooter(request):
	context = {
		"appFooter": 1
	}
	return render(request, "pages/layout-fixed-footer.html", context)

def layoutFullHeight(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": "p-0"
	}
	return render(request, "pages/layout-full-height.html", context)

def layoutFullWidth(request):
	context = {
		"appContentFullWidth": 1,
		"appSidebarHide": 1
	}
	return render(request, "pages/layout-full-width.html", context)

def layoutBoxedLayout(request):
	context = {
		"appBoxedLayout": 1,
		"bodyClass": "pace-top"
	}
	return render(request, "pages/layout-boxed-layout.html", context)

def layoutCollapsedSidebar(request):
	context = {
		"appSidebarCollapsed": 1
	}
	return render(request, "pages/layout-collapsed-sidebar.html", context)

def layoutTopNav(request):
	context = {
		"appTopNav": 1,
		"appSidebarHide": 1
	}
	return render(request, "pages/layout-top-nav.html", context)

def layoutMixedNav(request):
	context = {
		"appTopNav": 1,
	}
	return render(request, "pages/layout-mixed-nav.html", context)

def layoutMixedNavBoxedLayout(request):
	context = {
		"appTopNav": 1,
		"appBoxedLayout": 1
	}
	return render(request, "pages/layout-mixed-nav-boxed-layout.html", context)

def pageScrumBoard(request):
	return render(request, "pages/page-scrum-board.html")

def pageProduct(request):
	return render(request, "pages/page-product.html")

def pageProductDetails(request):
	return render(request, "pages/page-product-details.html")

def pageOrder(request):
	return render(request, "pages/page-order.html")

def pageOrderDetails(request):
	return render(request, "pages/page-order-details.html")

def pageGallery(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": 'p-0',
		"appSidebarCollapsed": 1
	}
	return render(request, "pages/page-gallery.html", context)

def pageSearchResults(request):
	return render(request, "pages/page-search-results.html")

def pageComingSoon(request):
	context = {
		"appSidebarHide": 1,
		"appHeaderHide": 1,
		"appContentClass": 'p-0'
	}
	return render(request, "pages/page-coming-soon.html", context)

def pageError(request):
	context = {
		"appSidebarHide": 1,
		"appHeaderHide": 1,
		"appContentClass": 'p-0'
	}
	return render(request, "pages/page-error.html", context)

def pageLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('DjangoHUDApp:analytics')
        else:
            messages.error(request, 'Invalid username or password.')
    
    context = {
        "appSidebarHide": 1,
        "appHeaderHide": 1,
        "appContentClass": 'p-0',
        "appContentFullWidth": 1,
        "appSidebarHide": 1,
        "appContentFullHeight": 1,
    }
    return render(request, "pages/page-login.html", context)

def pageRegister(request):
	context = {
		"appSidebarHide": 1,
		"appHeaderHide": 1,
		"appContentClass": 'p-0'
	}
	return render(request, "pages/page-register.html", context)

def pageMessenger(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": 'p-3'
	}
	return render(request, "pages/page-messenger.html", context)

def pageDataManagement(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": 'py-3'
	}
	return render(request, "pages/page-data-management.html", context)

def pageFileManager(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": 'd-flex flex-column'
	}
	return render(request, "pages/page-file-manager.html", context)

def pagePricing(request):
	return render(request, "pages/page-pricing.html")

def profile(request):
	return render(request, "pages/profile.html")

def calendar(request):
	context = {
		"appContentFullHeight": 1,
		"appContentClass": "p-0"
	}
	return render(request, "pages/calendar.html", context)

def settings(request):
	return render(request, "pages/settings.html")

def helper(request):
	return render(request, "pages/helper.html")
	

DjangoHUDApp/templates/partial/footer.html
<div id="footer" class="app-footer">
	&copy; 2024 SeanTheme All Right Reserved
</div>

DjangoHUDApp/templates/partial/header.html
<!-- BEGIN #header -->
<div id="header" class="app-header">
	{% if appSidebarHide is None %}
	<!-- BEGIN desktop-toggler -->
	<div class="desktop-toggler">
		<button type="button" class="menu-toggler" data-toggle-class="app-sidebar-collapsed" data-dismiss-class="app-sidebar-toggled" data-toggle-target=".app">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- BEGIN desktop-toggler -->
	
	<!-- BEGIN mobile-toggler -->
	<div class="mobile-toggler">
		<button type="button" class="menu-toggler" data-toggle="sidebar-mobile" data-bs-toggle="collapse" data-bs-target="#sidebar" data-toggle-class="app-sidebar-mobile-toggled" data-toggle-target=".app">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- END mobile-toggler -->
	{% endif %}
	{% if appTopNav is not None and appSidebarHide %}
	<!-- BEGIN desktop-toggler -->
	<div class="desktop-toggler">
		<button type="button" class="menu-toggler">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- BEGIN desktop-toggler -->
	<!-- BEGIN mobile-toggler -->
	<div class="mobile-toggler">
		<button type="button" class="menu-toggler" data-toggle="app-top-nav-mobile">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- END mobile-toggler -->
	{% endif %}
	
	<!-- BEGIN brand -->
	<div class="brand">
		{% comment %} <div class="desktop-toggler">
			<button type="button" class="menu-toggler" data-toggle="sidebar-minify">
				<span class="bar"></span>
				
			</button>
		</div> {% endcomment %}
		
		<a href="/" class="brand-logo">
			<span class="brand-img">
				<span class="brand-img-text text-theme">H</span>
			</span>
			<span class="brand-text">Sweetgirl</span>
		</a>
	</div>
	<!-- END brand -->
	
	<!-- BEGIN menu -->
	<div class="menu">
		<div class="menu-item dropdown dropdown-mobile-full">
			<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
				<div class="menu-icon"><i class="bi bi-grid-3x3-gap nav-icon"></i></div>
			</a>
			<div class="dropdown-menu fade dropdown-menu-end w-300px text-center p-0 mt-1">
				<div class="row row-grid gx-0">
					<div class="col-4">
						<a href="/email/inbox" class="dropdown-item text-decoration-none p-3 bg-none">
							<div class="position-relative">
								<i class="bi bi-circle-fill position-absolute text-theme top-0 mt-n2 me-n2 fs-6px d-block text-center w-100"></i>
								<i class="bi bi-envelope h2 opacity-5 d-block my-1"></i>
							</div>
							<div class="fw-500 fs-10px text-inverse">PRODUCTS</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/pos/customer-order" target="_blank" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-hdd-network h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">STOCK</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/calendar" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-calendar4 h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">CALENDAR</div>
						</a>
					</div>
				</div>
				<div class="row row-grid gx-0">
					<div class="col-4">
						<a href="/helper" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-terminal h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">CUSTOMERS</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/settings" class="dropdown-item text-decoration-none p-3 bg-none">
							<div class="position-relative">
								<i class="bi bi-circle-fill position-absolute text-theme top-0 mt-n2 me-n2 fs-6px d-block text-center w-100"></i>
								<i class="bi bi-sliders h2 opacity-5 d-block my-1"></i>
							</div>
							<div class="fw-500 fs-10px text-inverse">SETTINGS</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/widgets" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-collection-play h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">SALES</div>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="menu-item dropdown dropdown-mobile-full">
			<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
				<div class="menu-icon"><i class="bi bi-bell nav-icon"></i></div>
				<div class="menu-badge bg-theme"></div>
			</a>
			<div class="dropdown-menu dropdown-menu-end mt-1 w-300px fs-11px pt-1">
				<h6 class="dropdown-header fs-10px mb-1">NOTIFICATIONS</h6>
				<div class="dropdown-divider mt-1"></div>
				<a href="#" class="d-flex align-items-center py-10px dropdown-item text-wrap fw-semibold">
					<div class="fs-20px">
						<i class="bi bi-bag text-theme"></i>
					</div>
					<div class="flex-1 flex-wrap ps-3">
						<div class="mb-1 text-inverse">NEW ORDER RECEIVED ($1,299)</div>
						<div class="small text-inverse text-opacity-50">JUST NOW</div>
					</div>
					<div class="ps-2 fs-16px">
						<i class="bi bi-chevron-right"></i>
					</div>
				</a>
				<a href="#" class="d-flex align-items-center py-10px dropdown-item text-wrap fw-semibold">
					<div class="fs-20px w-20px">
						<i class="bi bi-person-circle text-theme"></i>
					</div>
					<div class="flex-1 flex-wrap ps-3">
						<div class="mb-1 text-inverse">3 NEW ACCOUNT CREATED</div>
						<div class="small text-inverse text-opacity-50">2 MINUTES AGO</div>
					</div>
					<div class="ps-2 fs-16px">
						<i class="bi bi-chevron-right"></i>
					</div>
				</a>
				<a href="#" class="d-flex align-items-center py-10px dropdown-item text-wrap fw-semibold">
					<div class="fs-20px w-20px">
						<i class="bi bi-gear text-theme"></i>
					</div>
					<div class="flex-1 flex-wrap ps-3">
						<div class="mb-1 text-inverse">SETUP COMPLETED</div>
						<div class="small text-inverse text-opacity-50">3 MINUTES AGO</div>
					</div>
					<div class="ps-2 fs-16px">
						<i class="bi bi-chevron-right"></i>
					</div>
				</a>
				<a href="#" class="d-flex align-items-center py-10px dropdown-item text-wrap fw-semibold">
					<div class="fs-20px w-20px">
						<i class="bi bi-grid text-theme"></i>
					</div>
					<div class="flex-1 flex-wrap ps-3">
						<div class="mb-1 text-inverse">WIDGET INSTALLATION DONE</div>
						<div class="small text-inverse text-opacity-50">5 MINUTES AGO</div>
					</div>
					<div class="ps-2 fs-16px">
						<i class="bi bi-chevron-right"></i>
					</div>
				</a>
				<a href="#" class="d-flex align-items-center py-10px dropdown-item text-wrap fw-semibold">
					<div class="fs-20px w-20px">
						<i class="bi bi-credit-card text-theme"></i>
					</div>
					<div class="flex-1 flex-wrap ps-3">
						<div class="mb-1 text-inverse">PAYMENT METHOD ENABLED</div>
						<div class="small text-inverse text-opacity-50">10 MINUTES AGO</div>
					</div>
					<div class="ps-2 fs-16px">
						<i class="bi bi-chevron-right"></i>
					</div>
				</a>
				<hr class="my-0">
				<div class="py-10px mb-n2 text-center">
					<a href="#" class="text-decoration-none fw-bold">SEE ALL</a>
				</div>
			</div>
		</div>
		<div class="menu-item dropdown dropdown-mobile-full">
			{% if user.is_authenticated %}
				<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
					<div class="menu-img online">
						{% load static %}
						<img src="{% static '/img/user/profile.jpg' %}" alt="Profile" height="60">
					</div>
					<div class="menu-text d-sm-block d-none w-170px">{{ user.username }}</div>
				</a>
				<div class="dropdown-menu dropdown-menu-end me-lg-3 fs-11px mt-1">
					<a class="dropdown-item d-flex align-items-center" href="/profile">PROFILE <i class="bi bi-person-circle ms-auto text-theme fs-16px my-n1"></i></a>
					<a class="dropdown-item d-flex align-items-center" href="/email/inbox">INBOX <i class="bi bi-envelope ms-auto text-theme fs-16px my-n1"></i></a>
					<a class="dropdown-item d-flex align-items-center" href="/calendar">CALENDAR <i class="bi bi-calendar ms-auto text-theme fs-16px my-n1"></i></a>
					<a class="dropdown-item d-flex align-items-center" href="/settings">SETTINGS <i class="bi bi-gear ms-auto text-theme fs-16px my-n1"></i></a>
					<div class="dropdown-divider"></div>
					<form method="post" action="{% url 'DjangoHUDApp:logout' %}" style="margin: 0;">
						{% csrf_token %}
						<button type="submit" class="dropdown-item d-flex align-items-center w-100 border-0 bg-transparent">
							LOGOUT <i class="bi bi-toggle-off ms-auto text-theme fs-16px my-n1"></i>
						</button>
					</form>
				</div>
			{% else %}
				<a href="{% url 'DjangoHUDApp:pageLogin' %}" class="menu-link ms-auto">
					<div class="menu-text d-flex justify-content-end">
						<button class="btn btn-theme btn-sm">LOGIN</button>
					</div>
				</a>
			{% endif %}
		</div>
	</div>
	<!-- END menu -->
	
	<!-- BEGIN menu-search -->
	<form class="menu-search" method="POST" name="header_search_form">
		<div class="menu-search-container">
			<div class="menu-search-icon"><i class="bi bi-search"></i></div>
			<div class="menu-search-input">
				<input type="text" class="form-control form-control-lg" placeholder="Search menu...">
			</div>
			<div class="menu-search-icon">
				<a href="#" data-toggle-class="app-header-menu-search-toggled" data-toggle-target=".app"><i class="bi bi-x-lg"></i></a>
			</div>
		</div>
	</form>
	<!-- END menu-search -->
</div>
<!-- END #header -->

DjangoHUDApp/templates/partial/scroll-top-btn.html
<!-- BEGIN btn-scroll-top -->
		<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>
		<!-- END btn-scroll-top -->

DjangoHUDApp/templates/partial/top-nav.html
<!-- BEGIN #top-nav -->
<div id="top-nav" class="app-top-nav">
	<!-- BEGIN menu -->
	<div class="menu">
		{% for menu in sidebar_menu %}
			{% if not menu.is_header and not menu.is_divider %}
				<div class="menu-item {% if menu.children %} has-sub {% endif %} {% if menu.is_active %} active {% endif %}">
					<a href="{{ menu.url }}" class="menu-link">
						<span class="menu-icon"><i class="{{ menu.icon }}"></i></span>
						<span class="menu-text">{{ menu.text }}</span>
						{% if menu.children %}
							<span class="menu-caret"><b class="caret"></b></span>
						{% endif %}
					</a>
					{% if menu.children %}
						<div class="menu-submenu">
							{% for children in menu.children %}
								<div class="menu-item {% if children.is_active %} active {% endif %}">
									<a href="{{ children.url }}" class="menu-link">
										<span class="menu-text">{{ children.text }}</span>
									</a>
								</div>
							{% endfor %}
						</div>
					{% endif %}
				</div>
			{% endif %}
		{% endfor %}
		<div class="menu-item menu-control menu-control-start">
			<a href="javascript:;" class="menu-link" data-toggle="app-top-menu-prev"><i class="bi bi-caret-left"></i></a>
		</div>
		<div class="menu-item menu-control menu-control-end">
			<a href="javascript:;" class="menu-link" data-toggle="app-top-menu-next"><i class="bi bi-caret-right"></i></a>
		</div>
	</div>
	<!-- END menu -->
</div>
<!-- END #top-nav -->